openapi: 3.1.0
info:
  title: Fake Perfect API
  description: A tiny API intentionally designed to have predictable behaviour. It
    exists so that Schemathesis-based tests can focus on the API contract rather than
    application logic.
  version: 1.0.0
paths:
  /status:
    get:
      tags:
      - health
      summary: Read Status
      description: Return the current status of the service.
      operationId: read_status_status_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
  /echo:
    post:
      tags:
      - utilities
      summary: Echo
      description: Return the provided message after applying deterministic transformations.
      operationId: echo_echo_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EchoRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inspect:
    get:
      tags:
      - utilities
      summary: Inspect
      description: Analyse a message and report simple textual characteristics.
      operationId: inspect_inspect_get
      parameters:
      - name: message
        in: query
        required: true
        schema:
          type: string
          maxLength: 1000
          minLength: 1
        description: Message to analyse for palindromic properties.
      - name: case_sensitive
        in: query
        required: false
        schema:
          type: boolean
          default: true
        description: If false, the palindrome check ignores character casing.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InspectResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    EchoRequest:
      properties:
        message:
          type: string
          maxLength: 1000
          minLength: 1
          title: Message
        repeat:
          type: integer
          maximum: 5.0
          minimum: 1.0
          title: Repeat
          default: 1
        uppercase:
          type: boolean
          title: Uppercase
          default: false
      additionalProperties: false
      type: object
      required:
      - message
      title: EchoRequest
      description: Input payload for the echo endpoint.
    EchoResponse:
      properties:
        result:
          type: string
          title: Result
          description: The transformed message.
        length:
          type: integer
          minimum: 0.0
          title: Length
        repeat:
          type: integer
          maximum: 5.0
          minimum: 1.0
          title: Repeat
        uppercase:
          type: boolean
          title: Uppercase
      type: object
      required:
      - result
      - length
      - repeat
      - uppercase
      title: EchoResponse
      description: Successful response payload for the echo endpoint.
    InspectResponse:
      properties:
        message:
          type: string
          maxLength: 1000
          minLength: 1
          title: Message
        mirrored:
          type: string
          maxLength: 1000
          minLength: 1
          title: Mirrored
        length:
          type: integer
          maximum: 1000.0
          minimum: 1.0
          title: Length
        is_palindrome:
          type: boolean
          title: Is Palindrome
        case_sensitive:
          type: boolean
          title: Case Sensitive
      type: object
      required:
      - message
      - mirrored
      - length
      - is_palindrome
      - case_sensitive
      title: InspectResponse
      description: Response payload for the message inspection endpoint.
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    StatusResponse:
      properties:
        status:
          type: string
          title: Status
          description: Health indicator for the service.
          default: ok
      type: object
      title: StatusResponse
      description: Response schema for the status endpoint.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
