name: Contract Testing

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  schemathesis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . schemathesis uvicorn
      - name: Launch API
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          python - <<'PY'
import socket, time
for _ in range(60):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        if sock.connect_ex(('127.0.0.1', 8000)) == 0:
            break
    time.sleep(1)
else:
    raise SystemExit('Server did not start in time')
PY
      - name: Run Schemathesis
        run: |
          schemathesis run http://127.0.0.1:8000/openapi.json \
            --workers 8 \
            --checks all \
            --exclude-checks response_headers_conformance
